create sequence CUSTOMERID_SEQ1 start with 1 increment by 1;

create table MYBANK_APP_CUSTOMER(
CUSTOMER_ID NUMBER(10),
CUSTOMER_NAME VARCHAR2(255) NOT NULL,
CUSTOMER_ADDRESS VARCHAR2(255) NOT NULL,
CUSTOMER_STATUS VARCHAR2(255) NOT NULL,
CUSTOMER_CONTACT NUMBER(10) NOT NULL,
USERNAME VARCHAR2(255) UNIQUE NOT NULL,
PASSWORD VARCHAR2(255) NOT NULL
);

alter table MYBANK_APP_CUSTOMER add constraint CUSTOMERID_SEQ1 primary key(CUSTOMER_ID);

--------------------
create sequence ACCOUNTID_SEQ1 start with 100 increment by 1;

create table MYBANK_APP_ACCOUNT(
ACCOUNT_ID NUMBER(10),
ACCOUNT_NUMBER NUMBER(20) UNIQUE NOT NULL,
CUSTOMER_ID NUMBER(10),
ACCOUNT_TYPE VARCHAR2(255) NOT NULL,
ACCOUNT_STATUS VARCHAR2(255) NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES MYBANK_APP_CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE
);

alter table MYBANK_APP_ACCOUNT add constraint ACCOUNTID_SEQ1 primary key(ACCOUNT_ID);

------------------------

create table MYBANK_APP_KYC(
KYC_NUMBER NUMBER(10) PRIMARY KEY,
CUSTOMER_ID NUMBER(10),
kYC_PAN VARCHAR2(255) UNIQUE NOT NULL,
KYC_AADHAAR NUMBER(12) UNIQUE NOT NULL,
KYC_STATUS VARCHAR2(255) NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES MYBANK_APP_CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE
);
--------

create sequence PAYEEID_SEQ1 start with 50 increment by 1;

create table MYBANK_APP_PAYEE(
PAYEE_ID NUMBER(10),
PAYEE_NAME VARCHAR2(255) NOT NULL,
SENDER_ACCOUNT_NUMBER NUMBER(20) NOT NULL,
BENEFICIARY_ACCOUNT_NUMBER NUMBER(20) NOT NULL,
FOREIGN KEY (BENEFICIARY_ACCOUNT_NUMBER) REFERENCES MYBANK_APP_ACCOUNT(ACCOUNT_NUMBER) ON DELETE CASCADE,
FOREIGN KEY (SENDER_ACCOUNT_NUMBER) REFERENCES MYBANK_APP_ACCOUNT(ACCOUNT_NUMBER) ON DELETE CASCADE);

alter table MYBANK_APP_PAYEE add constraint PAYEEID_SEQ1 primary key(PAYEE_ID);

---------------

create sequence TRANSACTIONID_SEQ1 start with 1000 increment by 1;

create table MYBANK_APP_TRANSACTION(
TRANSACTION_ID NUMBER(20),
TRANSACTION_TYPE VARCHAR2(255) NOT NULL,
TRANSACTION_FROM NUMBER(20),
TRANSACTION_TO NUMBER(20),
TRANSACTION_DATE DATE NOT NULL,
TRANSACTION_AMOUNT NUMBER(30) NOT NULL,
TRANSACTION_STATUS VARCHAR2(255) NOT NULL,
FOREIGN KEY (TRANSACTION_FROM) REFERENCES MYBANK_APP_ACCOUNT(ACCOUNT_NUMBER) ON DELETE CASCADE,
FOREIGN KEY (TRANSACTION_TO) REFERENCES MYBANK_APP_ACCOUNT(ACCOUNT_NUMBER) ON DELETE CASCADE
);

alter table MYBANK_APP_TRANSACTION add constraint TRANSACTIONID_SEQ1 primary key(TRANSACTION_ID);

---------------------

create sequence LOANID_SEQ1 start with 1500 increment by 1;

create table MYBANK_APP_LOAN_AVAILABLE(
LOAN_ID NUMBER(20),
LOAN_TYPE VARCHAR2(255) NOT NULL,
LOAN_NAME VARCHAR2(255) NOT NULL,
LOAN_DESCRIPTION VARCHAR2(255) NOT NULL,
LOAN_ROI NUMBER(10,2) NOT NULL);

ALTER TABLE MYBANK_APP_LOAN_AVAILABLE ADD CONSTRAINT LOANID_SEQ1 PRIMARY KEY(LOAN_ID);

--------------------

CREATE SEQUENCE LOANAPPID_SEQ1 START WITH 2000 INCREMENT BY 1;

CREATE TABLE MYBANK_APP_LOAN_AVAILED(
CUSTOMER_ID NUMBER(10),
LOAN_ID NUMBER(20),
LOANAPP_ID NUMBER(20),
LOAN_AMOUNT NUMBER(20) NOT NULL,
LOAN_EMI NUMBER(10,2) NOT NULL,
LOAN_TENURE NUMBER(10) NOT NULL,
FOREIGN KEY(LOAN_ID) REFERENCES MYBANK_APP_LOAN_AVAILABLE(LOAN_ID) ON DELETE CASCADE,
FOREIGN KEY(CUSTOMER_ID) REFERENCES MYBANK_APP_CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE);

ALTER TABLE MYBANK_APP_LOAN_AVAILED ADD CONSTRAINT LOANAPPID_SEQ1 PRIMARY KEY(LOANAPP_ID);

---------------------

CREATE TABLE MYBANK_APP_DEBITCARD(
ACCOUNT_NUMBER NUMBER(20),
CUSTOMER_ID NUMBER(10),
DEBITCARD_NUMBER NUMBER(10) PRIMARY KEY,
DEBITCARD_CVV NUMBER(5) NOT NULL,
DEBITCARD_PIN NUMBER(5) UNIQUE NOT NULL,
DEBITCARD_EXPIRY DATE NOT NULL,
DEBITCARD_STATUS VARCHAR2(255) NOT NULL,
DEBITCARD_DOMESTIC_LIMIT NUMBER(10) NOT NULL,
DEBITCARD_INTERNATIONAL_LIMIT NUMBER(10) NOT NULL,
FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES MYBANK_APP_ACCOUNT(ACCOUNT_NUMBER) ON DELETE CASCADE,
FOREIGN KEY(CUSTOMER_ID) REFERENCES MYBANK_APP_CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE);

---------------

CREATE SEQUENCE INSURANCEID_SEQ1 START WITH 20000 INCREMENT BY 1;

CREATE TABLE MYBANK_APP_INSURANCE_AVAILABLE(
INSURANCE_ID NUMBER(10),
INSURANCE_TYPE VARCHAR2(255) NOT NULL,
INSURANCE_NAME VARCHAR2(255) NOT NULL,
INSURANCE_KEY_BENEFITS VARCHAR2(255) NOT NULL,
INSURANCE_LIFETIME NUMBER(5) NOT NULL
);

ALTER TABLE MYBANK_APP_INSURANCE_AVAILABLE ADD CONSTRAINT INSURANCEID_SEQ1 PRIMARY KEY(INSURANCE_ID);

------------------

CREATE SEQUENCE INSURANCEAVAILEDID_SEQ1 START WITH 30000 INCREMENT BY 1;

CREATE TABLE MYBANK_APP_INSURANCE_AVAILED(
CUSTOMER_ID NUMBER(10),
INSURANCE_ID NUMBER(10),
INSURANCE_AVAILED_ID NUMBER(10),
INSURANCE_TYPE VARCHAR2(255) NOT NULL,
INSURANCE_NAME VARCHAR2(255) NOT NULL,
INSURANCE_KEY_BENEFITS VARCHAR2(255) NOT NULL,
INSURANCE_COVERAGE NUMBER(10) NOT NULL,
INSURANCE_LIFETIME NUMBER(5) NOT NULL,
INSURANCE_PREMIUM NUMBER(5) NOT NULL,
FOREIGN KEY(INSURANCE_ID) REFERENCES MYBANK_APP_INSURANCE_AVAILABLE(INSURANCE_ID) ON DELETE CASCADE,
FOREIGN KEY(CUSTOMER_ID) REFERENCES MYBANK_APP_CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE);

ALTER TABLE MYBANK_APP_INSURANCE_AVAILED ADD CONSTRAINT INSURANCEAVAILEDID_SEQ1 PRIMARY KEY(INSURANCE_AVAILED_ID);


-----------------

CREATE SEQUENCE DEPOSITEID_SEQ1 START WITH 40000 INCREMENT BY 1;

CREATE TABLE MYBANK_APP_DEPOSITS_AVAILABLE(
DEPOSITE_ID NUMBER(10),
DEPOSITE_NAME VARCHAR2(255) NOT NULL,
DEPOSITE_ROI NUMBER(10,2) NOT NULL,
DEPOSITE_TYPE VARCHAR2(255) NOT NULL,
DEPOSITE_DESCRIPTION VARCHAR2(255) NOT NULL);

ALTER TABLE MYBANK_APP_DEPOSITS_AVAILABLE ADD CONSTRAINT DEPOSITEID_SEQ1 PRIMARY KEY(DEPOSITE_ID);

------------------

CREATE SEQUENCE DEPOSITEAVAILID_SEQ1 START WITH 50000 INCREMENT BY 1;

CREATE TABLE MYBANK_APP_DEPOSITS_AVAILED(
CUSTOMER_ID NUMBER(10),
DEPOSITE_ID NUMBER(10),
DEPOSITE_AVAIL_ID NUMBER(10),
DEPOSITE_NAME VARCHAR2(255) NOT NULL,
DEPOSITE_ROI NUMBER(10,2) NOT NULL,
DEPOSITED_AMOUNT NUMBER(10) NOT NULL,
DEPOSITED_DURATION NUMBER(5) NOT NULL,
DEPOSIT_MATURITY NUMBER(5) NOT NULL,
FOREIGN KEY(DEPOSITE_ID) REFERENCES MYBANK_APP_DEPOSITS_AVAILABLE(DEPOSITE_ID) ON DELETE CASCADE,
FOREIGN KEY(CUSTOMER_ID) REFERENCES MYBANK_APP_CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE);

ALTER TABLE MYBANK_APP_DEPOSITS_AVAILED ADD CONSTRAINT DEPOSITEAVAILID_SEQ1 PRIMARY KEY(DEPOSITE_AVAIL_ID);

---------------------

