
package org.example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserSoap", targetNamespace = "http://example.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserSoap {


    /**
     * 
     * @param user
     */
    @WebMethod
    @Action(input = "http://example.org/UserSoap/createAccountRequest", output = "http://example.org/UserSoap/createAccountResponse")
    public void createAccount(
        @WebParam(name = "User", partName = "User")
        User user);

    /**
     * 
     * @param string
     * @return
     *     returns org.example.User
     */
    @WebMethod
    @WebResult(name = "Users", partName = "Users")
    @Action(input = "http://example.org/UserSoap/readByIdRequest", output = "http://example.org/UserSoap/readByIdResponse")
    public User readById(
        @WebParam(name = "String", partName = "String")
        String string);

    /**
     * 
     * @param string
     * @return
     *     returns org.example.TransactionGroup
     */
    @WebMethod
    @WebResult(name = "TransactionGroup", partName = "TransactionGroup")
    @Action(input = "http://example.org/UserSoap/readAllByIdRequest", output = "http://example.org/UserSoap/readAllByIdResponse")
    public TransactionGroup readAllById(
        @WebParam(name = "String", partName = "String")
        String string);

}
